name: Custom Rom Builder Samsung Galaxy A11/M11

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'direct link for Gsi image '
        required: true
        default: 'https://sourceforge.net/projects/andyyan-gsi/files/lineage-19.x/lineage-19.1-20230715-UNOFFICIAL-a64_bgN.img.xz'        
      ARCH:
        description: 'ARM64 or ARM32?'
        required: true
        default: '32'                
      NAME:
        description: 'Rom Name'
        required: true
        default: 'LineageOS_19.1_A11_M11_ARM32_Gapps'                

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Freeing Up Disk Space
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/libexec/docker

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
          wget -O a11o.zip "https://2111.filemail.com/api/file/get?filekey=MOhjkSHHosACMBf63Av_8RQXu84wAvWh087wp5WvDPY6L4nq_qDKVreM"
          unzip a11o.zip
          rm a11o.zip

    - name: Downloading your GSI
      run: |
          mkdir -p ./temp
          wget -O ./temp/gsi_system "${{ github.event.inputs.GSI }}"

    - name: Extracting GSI if compressed
      run: |
          cd ./temp
          if file gsi_system | grep -q "XZ compressed data"; then
            echo "Detected XZ archive. Decompressing..."
            mv gsi_system gsi_system.img.xz
            xz -d gsi_system.img.xz
            mv gsi_system.img system.img
          else
            echo "Detected raw image file. Proceeding..."
            mv gsi_system system.img
          fi
          cd ..

    - name: Building
      run: |
          chmod +x ./xz
          chmod +x ./size
          bash ./xz
          
    - name: Uploading The Zip
      uses: actions/upload-artifact@v4
      with:
          name: RisingOS-7.0-Galaxy-A11-M11
          path: ./*.xz
